# Generated by Django 4.1.5 on 2023-02-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='date_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
